export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8080/api/v1',
  JWT_STORAGE_KEY: process.env.NEXT_PUBLIC_JWT_STORAGE_KEY || 'authToken',
  REFRESH_TOKEN_STORAGE_KEY: process.env.NEXT_PUBLIC_REFRESH_TOKEN_STORAGE_KEY || 'refreshToken',
  USER_STORAGE_KEY: process.env.NEXT_PUBLIC_USER_STORAGE_KEY || 'user',
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || '',
  GOOGLE_REDIRECT_URI: process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URI || 'http://localhost:3000/auth/callback',
  ADMIN_EMAIL: process.env.NEXT_PUBLIC_ADMIN_EMAIL || '',
  TIMEOUT: 10000,
  MAX_RETRIES: 3,
  RETRY_DELAY: 1000,
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    PROFILE: '/auth/profile',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    GOOGLE: '/auth/google',
    GOOGLE_CALLBACK: '/auth/google/callback',
    GOOGLE_USER: '/auth/google/user',
  },
  PROJECTS: {
    LIST: '/projects',
    BY_ID: (id: string) => `/projects/${id}`,
    BY_SLUG: (slug: string) => `/projects/slug/${slug}`,
    CREATE: '/projects',
    UPDATE: (id: string) => `/projects/${id}`,
    DELETE: (id: string) => `/projects/${id}`,
    FEATURED: '/projects/featured',
    BY_CATEGORY: (category: string) => `/projects/category/${category}`,
    SEARCH: '/projects/search',
  },
  CONTACT: {
    SUBMIT: '/contact',
    LIST: '/contact',
    BY_ID: (id: string) => `/contact/${id}`,
    UPDATE: (id: string) => `/contact/${id}`,
    DELETE: (id: string) => `/contact/${id}`,
    STATS: '/contact/stats',
    MARK_READ: (id: string) => `/contact/${id}/read`,
    MARK_REPLIED: (id: string) => `/contact/${id}/replied`,
    ARCHIVE: (id: string) => `/contact/${id}/archive`,
  },
  STATUS: {
    CURRENT: '/status/current',
    MY_STATUS: '/status/me',
    SET: '/status',
    UPDATE: (id: string) => `/status/${id}`,
    CLEAR: '/status/current',
    HISTORY: '/status/history',
  },
  TEST: {
    EMAIL: '/test/email',
    HEALTH: '/test/health',
  },
}; 
